spring:
  application:
    name: LISTA
  config:
    activate:
      on-profile: dev
  cloud:
    loadbalancer:
      enabled: true
      ribbon:
        enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/glaiss?currentSchema=public&stringtype=unspecified&applicationName=app&options=-c%20TimeZone=UTC
    username: att_lista
    password: lista_ddl_SaintBier
    driver-class-name: org.postgresql.Driver
  flyway:
    user: att_lista
    password: lista_ddl_SaintBier
    locations: classpath:db/migration
    table: FLYWAY_SCHEMA_HISTORY
    schemas: att_lista
  jackson:
    time-zone: America/Sao_Paulo
  jpa:
    enabled: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  timezone: America/Sao_Paulo
server:
  port: ${PORT:8193}
  servlet:
    context-path: /lista

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/discovery/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    exporter:
      zipkin:
        enabled: true
        url: http://localhost:9411/api/v2/spans
security:
  oauth2:
    client:
      client-id: lista
      secret: bael-secret
    resource:
      filter-order: 3
      jwt:
        key: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhocpCKsOQEoButV4V76t0S2Vdd6iMUiud/q5Qvt/MQb9JoXWnx/rlYhVsyr20jrIEgfTGU51oJaGZRovAVNuQLF0VlK/bUu9a4Ce5PRAEeWPdTFrFEdxTIBdG0gsbZlb/SotY6jW+zI+wJI3Yl5Lm9+tHx
          LeCqCtLrXWCHngGnU9eLsEa1OR94aR9gcIuUJhu/QjSDbARjoNYv7FSnBFeXYqahcT3WGcos7M2RZh6SZnVlN7aZ+Ve1CVv5BCVJf7lwEpGEJjGtipx6XJoERO7jPhwie+dYmcpP4yTCvqGlTGPWyYPyi6QBZPznkcCKcqs2MPtXnNUm0PuLkyaMycvwIDAQAB
          -----END PUBLIC KEY-----