CREATE TABLE IF NOT EXISTS VENDEDORES (
  ID UUID NOT NULL,
  NOME VARCHAR(250) NOT NULL,
  CNPJ varchar(14) NULL,
  CREATED_DATE TIMESTAMP WITH TIME ZONE NULL,
  MODIFIED_DATE TIMESTAMP WITH TIME ZONE NULL,
  CREATED_BY VARCHAR(100) NULL,
  MODIFIED_BY VARCHAR(100) NULL,
  VERSION BIGINT DEFAULT 0,
  CONSTRAINT PK_VENDEDORES_ID PRIMARY KEY (ID),
  CONSTRAINT UNQ_VENDEDOR_CNPJ UNIQUE (CNPJ)
);

CREATE TABLE IF NOT EXISTS ENDERECOS (
  ID UUID NOT NULL,
  VENDEDOR_ID UUID NOT NULL,
  COMPLEMENTO VARCHAR(100) NULL,
  CEP VARCHAR(13) NOT NULL,
  LOGRADOURO VARCHAR(100) NOT NULL,
  BAIRRO VARCHAR(50) NOT NULL,
  CIDADE VARCHAR(40) NOT NULL,
  NUMERO VARCHAR(20) NOT NULL,
  ESTADO VARCHAR(80) NOT NULL,
  VERSION BIGINT DEFAULT 0,
  CREATED_DATE TIMESTAMP WITH TIME ZONE NULL,
  MODIFIED_DATE TIMESTAMP WITH TIME ZONE NULL,
  CREATED_BY VARCHAR(100) NULL,
  MODIFIED_BY VARCHAR(100) NULL,
  CONSTRAINT PK_ENDERECOS_ID PRIMARY KEY (ID),
  CONSTRAINT FK_VENDEDOR_ID FOREIGN KEY (VENDEDOR_ID) REFERENCES VENDEDORES (ID)
);

CREATE TABLE IF NOT EXISTS STATUS_LISTA (
  CODIGO VARCHAR(10) NOT NULL,
  DESCRICAO VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  MODIFIED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  CREATED_BY VARCHAR(100) NOT NULL,
  MODIFIED_BY VARCHAR(100) NOT NULL,
  VERSION BIGINT DEFAULT 0,
  CONSTRAINT PK_STATUS_LISTA_CODIGO PRIMARY KEY (CODIGO)
);

CREATE TABLE IF NOT EXISTS LISTAS_COMPRA (
  ID UUID NOT NULL,
  USUARIO_ID UUID NOT NULL,
  STATUS_LISTA_CODIGO VARCHAR(10) NOT NULL,
  NOME VARCHAR(30) NOT NULL,
  VALOR_TOTAL NUMERIC(10, 2) NOT NULL,
  TOTAL_ITENS SMALLINT NOT NULL,
  CREATED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  MODIFIED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  CREATED_BY VARCHAR(100) NOT NULL,
  MODIFIED_BY VARCHAR(100) NOT NULL,
  VERSION BIGINT DEFAULT 0,
  CONSTRAINT PK_LISTAS_COMPRA_ID PRIMARY KEY (ID),
  CONSTRAINT FK_LISTAS_COMPRA_STATUS_LISTA_CODIGO FOREIGN KEY (STATUS_LISTA_CODIGO) REFERENCES STATUS_LISTA (CODIGO)
);

CREATE TABLE IF NOT EXISTS ITENS (
  ID UUID NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  DESCRICAO VARCHAR(100) NOT NULL,
  IS_ATIVO BOOLEAN DEFAULT TRUE NOT NULL,
  EAN VARCHAR(14) NULL,
  UNIDADE_PADRAO VARCHAR(10) NULL,
  CREATED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  MODIFIED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  CREATED_BY VARCHAR(100) NOT NULL,
  MODIFIED_BY VARCHAR(100) NOT NULL,
  VERSION BIGINT DEFAULT 0,
  CONSTRAINT PK_ITENS_ID PRIMARY KEY (ID),
  CONSTRAINT UNQ_ITEM_EAN UNIQUE (EAN)
);

CREATE TABLE IF NOT EXISTS STATUS_PRECO_REPORTADO (
  CODIGO VARCHAR(30) NOT NULL,
  DESCRICAO VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  MODIFIED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  CREATED_BY VARCHAR(100) NOT NULL,
  MODIFIED_BY VARCHAR(100) NOT NULL,
  VERSION BIGINT DEFAULT 0,
  CONSTRAINT PK_STATUS_PRECO_REPORTADO_CODIGO PRIMARY KEY (CODIGO)
);

CREATE TABLE IF NOT EXISTS ITENS_OFERTA (
  ID UUID NOT NULL,
  ITEM_ID UUID NOT NULL,
  VENDEDOR_ID UUID NOT NULL,
  HAS_PROMOCAO_ATIVA BOOLEAN DEFAULT FALSE NOT NULL,
  PRECO NUMERIC(10, 2) NOT NULL,
  DATA_INICIO_PROMOCAO TIMESTAMP WITH TIME ZONE NULL,
  DATA_FINAL_PROMOCAO TIMESTAMP WITH TIME ZONE NULL,
  ORIGEM_PRECO VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
  CREATED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  MODIFIED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  CREATED_BY VARCHAR(100) NOT NULL,
  MODIFIED_BY VARCHAR(100) NOT NULL,
  VERSION BIGINT DEFAULT 0,
  CONSTRAINT PK_ITENS_OFERTA_ID PRIMARY KEY (ID),
  CONSTRAINT FK_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITENS (ID),
  CONSTRAINT FK_VENDEDOR_ID FOREIGN KEY (VENDEDOR_ID) REFERENCES VENDEDORES (ID),
  CONSTRAINT UNQ_ITEM_VENDEDOR UNIQUE (ITEM_ID, VENDEDOR_ID)
);

CREATE TABLE IF NOT EXISTS HISTORICO_PRECOS (
  ID UUID NOT NULL,
  ITEM_OFERTA_ID UUID NOT NULL,
  PRECO NUMERIC(10, 2) NOT NULL,
  HAS_PROMOCAO_ATIVA BOOLEAN DEFAULT FALSE NOT NULL,
  DATA_REFERENCIA TIMESTAMP WITH TIME ZONE NULL,
  CREATED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  MODIFIED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  CREATED_BY VARCHAR(100) NOT NULL,
  MODIFIED_BY VARCHAR(100) NOT NULL,
  VERSION BIGINT DEFAULT 0,
  CONSTRAINT PK_HISTORICO_PRECOS_ID PRIMARY KEY (ID),
  CONSTRAINT FK_ITEM_OFERTA_ID FOREIGN KEY (ITEM_OFERTA_ID) REFERENCES ITENS_OFERTA (ID)
);

CREATE TABLE IF NOT EXISTS PRECOS_REPORTADOS_PENDENTES (
  ID UUID NOT NULL,
  ITEM_OFERTA_ID UUID NOT NULL,
  STATUS_PRECO_REPORTADO VARCHAR(30) NOT NULL,
  PRECO NUMERIC(10, 2) NOT NULL,
  MENSAGEM_ERRO VARCHAR(250) NULL,
  TENTATIVAS SMALLINT NOT NULL,
  HAS_PROMOCAO_ATIVA BOOLEAN DEFAULT FALSE NOT NULL,
  DATA_INICIO_PROMOCAO TIMESTAMP WITH TIME ZONE NULL,
  DATA_FINAL_PROMOCAO TIMESTAMP WITH TIME ZONE NULL,
  CREATED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  MODIFIED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  CREATED_BY VARCHAR(100) NOT NULL,
  MODIFIED_BY VARCHAR(100) NOT NULL,
  VERSION BIGINT DEFAULT 0,
  CONSTRAINT PK_PRECOS_REPORTADOS_PENDENTES_ID PRIMARY KEY (ID),
  CONSTRAINT FK_ITENS_OFERTA_ID FOREIGN KEY (ITEM_OFERTA_ID) REFERENCES ITENS_OFERTA (ID),
  CONSTRAINT FK_STATUS_PRECO_REPORTADO FOREIGN KEY (STATUS_PRECO_REPORTADO) REFERENCES STATUS_PRECO_REPORTADO (CODIGO)
);

CREATE TABLE IF NOT EXISTS ITENS_LISTA (
  ID UUID NOT NULL,
  LISTAS_COMPRA_ID UUID NULL,
  ITEM_OFERTA_ID UUID NOT NULL,
  QUANTIDADE SMALLINT NOT NULL,
  PRECO_UNITARIO NUMERIC(10,2) NULL,
  CREATED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  MODIFIED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  CREATED_BY VARCHAR(100) NOT NULL,
  MODIFIED_BY VARCHAR(100) NOT NULL,
  VERSION BIGINT DEFAULT 0,
  CONSTRAINT PK_ITENS_LISTA_ID PRIMARY KEY (ID),
  CONSTRAINT FK_LISTAS_COMPRA_ID FOREIGN KEY (LISTAS_COMPRA_ID) REFERENCES LISTAS_COMPRA (ID),
  CONSTRAINT FK_ITEM_OFERTA_ID FOREIGN KEY (ITEM_OFERTA_ID) REFERENCES ITENS_OFERTA (ID)
);

CREATE TABLE NOTAS_FISCAIS (
  ID UUID NOT NULL,
  CHAVE_ACESSO VARCHAR(44) NOT NULL,
  MODELO VARCHAR(2) NOT NULL, -- 65
  DATA_EMISSAO TIMESTAMP WITH TIME ZONE NOT NULL,
  VALOR_TOTAL NUMERIC(10,2) NOT NULL,
  VENDEDOR_ID UUID NOT NULL,
  XML_HASH VARCHAR(64) NOT NULL,
  CREATED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT PK_NOTAS_FISCAIS PRIMARY KEY (ID),
  CONSTRAINT UNQ_NF_CHAVE UNIQUE (CHAVE_ACESSO),
  CONSTRAINT FK_NF_VENDEDOR FOREIGN KEY (VENDEDOR_ID) REFERENCES VENDEDORES(ID)
);

CREATE TABLE ITENS_NOTA_FISCAL (
  ID UUID NOT NULL,
  NOTA_FISCAL_ID UUID NOT NULL,
  ITEM_ID UUID NOT NULL,
  QUANTIDADE NUMERIC(10,4) NOT NULL,
  UNIDADE VARCHAR(10) NOT NULL,
  PRECO_UNITARIO NUMERIC(10,2) NOT NULL,
  PRECO_TOTAL NUMERIC(10,2) NOT NULL,
  CREATED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT PK_ITENS_NF PRIMARY KEY (ID),
  CONSTRAINT FK_ITENS_NF_NF FOREIGN KEY (NOTA_FISCAL_ID) REFERENCES NOTAS_FISCAIS(ID),
  CONSTRAINT FK_ITENS_NF_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITENS(ID)
);