CREATE TABLE IF NOT EXISTS VENDEDORES (
  ID UUID NOT NULL,
  NOME VARCHAR(250) NOT NULL,
  CREATED_DATE TIMESTAMP WITH TIME ZONE NULL,
  MODIFIED_DATE TIMESTAMP WITH TIME ZONE NULL,
  CREATED_BY VARCHAR(100) NULL,
  MODIFIED_BY VARCHAR(100) NULL,
  CONSTRAINT PK_VENDEDORES_ID PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ENDERECOS (
  ID UUID NOT NULL,
  VENDEDOR_ID UUID NOT NULL,
  COMPLEMENTO VARCHAR(100) NOT NULL,
  CEP VARCHAR(13) NOT NULL,
  LOGRADOURO VARCHAR(100) NOT NULL,
  BAIRRO VARCHAR(50) NOT NULL,
  CIDADE VARCHAR(40) NOT NULL,
  NUMERO VARCHAR(20) NOT NULL,
  ESTADO VARCHAR(80) NOT NULL,
  CREATED_DATE TIMESTAMP WITH TIME ZONE NULL,
  MODIFIED_DATE TIMESTAMP WITH TIME ZONE NULL,
  CREATED_BY VARCHAR(100) NULL,
  MODIFIED_BY VARCHAR(100) NULL,
  CONSTRAINT PK_ENDERECOS_ID PRIMARY KEY (ID),
  CONSTRAINT FK_VENDEDOR_ID FOREIGN KEY (VENDEDOR_ID) REFERENCES VENDEDORES (ID)
);

CREATE TABLE IF NOT EXISTS LISTAS_COMPRA (
  ID UUID NOT NULL,
  USUARIO_ID UUID NOT NULL,
  VALOR_TOTAL NUMERIC(10, 2) NOT NULL,
  TOTAL_ITENS SMALLINT NOT NULL,
  CREATED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  MODIFIED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  CREATED_BY VARCHAR(100) NOT NULL,
  MODIFIED_BY VARCHAR(100) NOT NULL,
  VERSION BIGINT DEFAULT 0,
  CONSTRAINT PK_LISTAS_COMPRA_ID PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ITENS (
  ID UUID NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  DESCRICAO VARCHAR(100) NOT NULL,
  IS_ATIVO BOOLEAN DEFAULT TRUE NOT NULL,
  CREATED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  MODIFIED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  CREATED_BY VARCHAR(100) NOT NULL,
  MODIFIED_BY VARCHAR(100) NOT NULL,
  VERSION BIGINT DEFAULT 0,
  CONSTRAINT PK_ITENS_ID PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS STATUS_PRECO_REPORTADO (
  CODIGO VARCHAR(30) NOT NULL,
  DESCRICAO VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  MODIFIED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  CREATED_BY VARCHAR(100) NOT NULL,
  MODIFIED_BY VARCHAR(100) NOT NULL,
  VERSION BIGINT DEFAULT 0,
  CONSTRAINT PK_CODIGO PRIMARY KEY (CODIGO)
);

CREATE TABLE IF NOT EXISTS ITENS_OFERTA (
  ID UUID NOT NULL,
  ITEM_ID UUID NOT NULL,
  VENDEDOR_ID UUID NOT NULL,
  HAS_PROMOCAO_ATIVA BOOLEAN DEFAULT FALSE NOT NULL,
  PRECO NUMERIC(10, 2) NOT NULL,
  DATA_INICIO_PROMOCAO TIMESTAMP WITH TIME ZONE NULL,
  DATA_FINAL_PROMOCAO TIMESTAMP WITH TIME ZONE NULL,
  CREATED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  MODIFIED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  CREATED_BY VARCHAR(100) NOT NULL,
  MODIFIED_BY VARCHAR(100) NOT NULL,
  VERSION BIGINT DEFAULT 0,
  CONSTRAINT PK_ITENS_OFERTA_ID PRIMARY KEY (ID),
  CONSTRAINT FK_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITENS (ID),
  CONSTRAINT FK_VENDEDOR_ID FOREIGN KEY (VENDEDOR_ID) REFERENCES VENDEDORES (ID),
  CONSTRAINT UNQ_ITEM_VENDEDOR UNIQUE (ITEM_ID, VENDEDOR_ID)
);

CREATE TABLE IF NOT EXISTS HISTORICO_PRECOS (
  ID UUID NOT NULL,
  ITEM_OFERTA_ID UUID NOT NULL,
  PRECO NUMERIC(10, 2) NOT NULL,
  HAS_PROMOCAO_ATIVA BOOLEAN DEFAULT FALSE NOT NULL,
  CREATED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  MODIFIED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  CREATED_BY VARCHAR(100) NOT NULL,
  MODIFIED_BY VARCHAR(100) NOT NULL,
  VERSION BIGINT DEFAULT 0,
  CONSTRAINT PK_HISTORICO_PRECOS_ID PRIMARY KEY (ID),
  CONSTRAINT FK_ITEM_OFERTA_ID FOREIGN KEY (ITEM_OFERTA_ID) REFERENCES ITENS_OFERTA (ID)
);

CREATE TABLE IF NOT EXISTS PRECOS_REPORTADOS_PENDENTES (
  ID UUID NOT NULL,
  ITEM_OFERTA_ID UUID NOT NULL,
  STATUS_PRECO_REPORTADO VARCHAR(30) NOT NULL,
  PRECO NUMERIC(10, 2) NOT NULL,
  MENSAGEM_ERRO VARCHAR(250) NULL,
  TENTATIVAS SMALLINT NOT NULL,
  HAS_PROMOCAO_ATIVA BOOLEAN DEFAULT FALSE NOT NULL,
  DATA_INICIO_PROMOCAO TIMESTAMP WITH TIME ZONE NULL,
  DATA_FINAL_PROMOCAO TIMESTAMP WITH TIME ZONE NULL,
  CREATED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  MODIFIED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  CREATED_BY VARCHAR(100) NOT NULL,
  MODIFIED_BY VARCHAR(100) NOT NULL,
  VERSION BIGINT DEFAULT 0,
  CONSTRAINT PK_PRECOS_REPORTADOS_PENDENTES_ID PRIMARY KEY (ID),
  CONSTRAINT FK_ITENS_OFERTA_ID FOREIGN KEY (ITEM_OFERTA_ID) REFERENCES ITENS_OFERTA (ID),
  CONSTRAINT FK_STATUS_PRECO_REPORTADO FOREIGN KEY (STATUS_PRECO_REPORTADO) REFERENCES STATUS_PRECO_REPORTADO (CODIGO)
);

CREATE TABLE IF NOT EXISTS ITENS_LISTA (
  ID UUID NOT NULL,
  LISTAS_COMPRA_ID UUID NULL,
  ITEM_OFERTA_ID UUID NOT NULL,
  QUANTIDADE SMALLINT NOT NULL,
  CREATED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  MODIFIED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  CREATED_BY VARCHAR(100) NOT NULL,
  MODIFIED_BY VARCHAR(100) NOT NULL,
  VERSION BIGINT DEFAULT 0,
  CONSTRAINT PK_ITENS_LISTA_ID PRIMARY KEY (ID),
  CONSTRAINT FK_LISTAS_COMPRA_ID FOREIGN KEY (LISTAS_COMPRA_ID) REFERENCES LISTAS_COMPRA (ID),
  CONSTRAINT FK_ITEM_OFERTA_ID FOREIGN KEY (ITEM_OFERTA_ID) REFERENCES ITENS_OFERTA (ID)
);