CREATE TABLE ITENS
(
    ID            UUID                     NOT NULL CONSTRAINT PK_ITENS_ID PRIMARY KEY,
    NOME          VARCHAR(250)             NOT NULL,
    PESO          VARCHAR(10)              NOT NULL,
    MARCA         VARCHAR(10)              NOT NULL,
    CREATED_DATE  TIMESTAMP WITH TIME ZONE NOT NULL,
    MODIFIED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY    VARCHAR(100)             NOT NULL,
    MODIFIED_BY   VARCHAR(100)             NOT NULL
);

CREATE TABLE PRECOS
(
    ID            UUID                     NOT NULL CONSTRAINT PK_PRECOS_ID PRIMARY KEY,
    VALOR         NUMERIC(10, 2)           NOT NULL,
    LOCAL_ID      UUID                     NOT NULL,
    ITEM_ID       UUID                     NOT NULL CONSTRAINT FK_PRECOS_ITEM_ID REFERENCES ITENS ( ID ),
    CREATED_DATE  TIMESTAMP WITH TIME ZONE NOT NULL,
    MODIFIED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY    VARCHAR(100)             NOT NULL,
    MODIFIED_BY   VARCHAR(100)             NOT NULL
);

 CREATE TABLE LISTAS_COMPRA (
    ID                   UUID                       NOT NULL CONSTRAINT PK_LISTAS_COMPRA_ID PRIMARY KEY,
    USUARIO_ID           UUID                       NOT NULL,
    VALOR_TOTAL          NUMERIC(10,2)              NOT NULL,
    CREATED_DATE         TIMESTAMP WITH TIME ZONE   NOT NULL,
    MODIFIED_DATE        TIMESTAMP WITH TIME ZONE   NOT NULL,
    CREATED_BY           VARCHAR(100)               NOT NULL,
    MODIFIED_BY          VARCHAR(100)               NOT NULL
 );

CREATE TABLE ITENS_LISTA
(
    ID                  UUID                        NOT NULL CONSTRAINT PK_ITENS_LISTA_ID PRIMARY KEY,
    ITEM_ID             UUID                        NOT NULL CONSTRAINT FK_ITENS_LISTA_ITEM_ID REFERENCES ITENS ( ID ),
    LISTA_COMPRA_ID     UUID                        NOT NULL CONSTRAINT FK_ITENS_LISTA_LISTA_COMPRA_ID REFERENCES LISTAS_COMPRA ( ID ),
    PRECO               NUMERIC(10, 2)              NOT NULL,
    QUANTIDADE          INTEGER                     NOT NULL,
    CREATED_DATE        TIMESTAMP WITH TIME ZONE    NOT NULL,
    MODIFIED_DATE       TIMESTAMP WITH TIME ZONE    NOT NULL,
    CREATED_BY          VARCHAR(100)                NOT NULL,
    MODIFIED_BY         VARCHAR(100)                NOT NULL
);
